# Generated by Django 4.2.5 on 2023-10-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenapiFile',
            fields=[
                ('name', models.CharField(max_length=511, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schema', models.JSONField()),
            ],
        ),
    ]
